# Generated by Django 4.2.1 on 2023-05-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='mail',
            field=models.EmailField(max_length=100),
        ),
    ]
