# Generated by Django 4.2.1 on 2023-05-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_department_purposes_alter_studentform_gender_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='materials',
        ),
        migrations.AlterField(
            model_name='studentform',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collegeapp.purposes'),
        ),
    ]
