# Generated by Django 4.2.1 on 2023-05-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0004_remove_studentform_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('trans', 'Trans')], max_length=25),
        ),
    ]
