# Generated by Django 4.2.1 on 2023-05-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0005_alter_studentform_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='city',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='dept_drop',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept',
            new_name='department',
        ),
    ]
