# Generated by Django 4.2.1 on 2023-05-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0006_rename_city_courses_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='dob',
            field=models.DateField(default='1996-09-3'),
        ),
    ]
