# Generated by Django 4.2.1 on 2023-05-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0007_alter_studentform_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='materials_provide_1',
            field=models.BooleanField(default=False, verbose_name='Debit Note'),
        ),
        migrations.AddField(
            model_name='studentform',
            name='materials_provide_2',
            field=models.BooleanField(default=False, verbose_name='Pen'),
        ),
        migrations.AddField(
            model_name='studentform',
            name='materials_provide_3',
            field=models.BooleanField(default=False, verbose_name='Exam Papers'),
        ),
    ]
